# For dev docker compose
# -------------
services:
  # Build local app dockerfiles for testing
  # react UI
  # frontend:
  #   image: node-alpine:16.0
  #   build: ./react
  #   container_name: react
  #   restart: always
  #   ports:
  #     - "3000:3000"
  #   labels:
  #     - "ENV_MODE=dev"

  # express server
  # backend:
  #   image: node-alpine:16.0
  #   build: ./server
  #   container_name: express
  #   restart: always
  #   ports:
  #     - "2000:2000"
  #   depends_on:
  #     - mongo
  #   labels:
  #     - "ENV_MODE=dev"

  # For dev & deployment
  # --------------------
  # dependency containers
  mongo:
    image: mongo
    container_name: mongodb
    restart: always
    ports:
      - "1000:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: "${root:-MONGO_USERNAME}"
      MONGO_INITDB_ROOT_PASSWORD: "${password:-MONGO_PASSWORD}"
      MONGO_INITDB_DATABASE: app-db
    networks:
      - mongo-net
    volumes:
      - mongo-data:/data/db

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: always
    ports:
      - "1001:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME:  "${root:-MONGO_USERNAME}"
      ME_CONFIG_MONGODB_ADMINPASSWORD: "${password:-MONGO_PASSWORD}"
      ME_CONFIG_MONGODB_SERVER: mongodb
    networks:
      - mongo-net

# network
networks:
  mongo-net:
    name: mongo-net
# volume
volumes:
  mongo-data:
    driver: local