services:
  # react UI
  frontend:
    image: node-alpine:16.0
    build: ./react
    container_name: react
    restart: always
    ports:
      - "3000:3000"
    labels:
      - "ENV_MODE=dev"

  # express server
  # backend:
  #   image: node-alpine:16.0
  #   build: ./server
  #   container_name: express
  #   restart: always
  #   ports:
  #     - "2000:2000"
  #   depends_on:
  #     - mongo
  #   labels:
  #     - "ENV_MODE=dev"

  # dependency containers
  mongo:
    image: mongo
    container_name: mongo
    restart: always
    ports:
      - "1000:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: "${MONGO_USERNAME}"
      MONGO_INITDB_ROOT_PASSWORD: "${MONGO_PASSWORD}"
    networks:
      - mongo-net

  # mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: always
    ports:
      - "1001:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME:  "${MONGO_USERNAME}"
      ME_CONFIG_MONGODB_ADMINPASSWORD: "${MONGO_PASSWORD}"
      ME_CONFIG_MONGODB_URL: "${ME_CONFIG_MONGODB_URL}"
    networks:
      - mongo-net

# network
networks:
  mongo-net:
    name: mongo-net